server:
  listen-address: 0.0.0.0:9000

database:
  type: sqlite
  database: dev.db
  # username: your_db_username
  # password: your_db_password
  # address: your_database_address
  # port: 21024
  # use-tls: false

auth:
  jwt-key: "your_jwt_key"

proxy:
  cache-expiration-seconds: 60